version: '3'

services:
  mariadb:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: user
    ports:
      - "3306:3306"
      -
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart:
        always
    depends_on:
      - mariadb
      - email-service
    ports:
      - "8080:8080"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"

  email-service:
    build:
      context: ./email-user/
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
      - mailhog
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
